apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-parameter-uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-parameter-uploader
  template:
    metadata:
      labels:
        app: aws-parameter-uploader
    spec:
      containers:
        - name: uploader
          image: 626890267457.dkr.ecr.ap-south-1.amazonaws.com/aws-parameter-uploader:latest
          ports:
            - containerPort: 8080
