apiVersion: v1
kind: Service
metadata:
  name: aws-parameter-uploader
  namespace: aws-parameter-uploader
spec:
  selector:
    app: aws-parameter-uploader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
