name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build test
        run: mvn test

      - name: Build WAR
        run: mvn clean package

      - name: Log in to Amazon ECR 1
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.BUILD_ECR_URL }}
      - name: Push Docker Image to ECR
        run: |
              REPO_NAME=${GITHUB_REPOSITORY#"vsbopi/"}
              IMAGE_TAG=$GITHUB_RUN_ID
              docker build . -t ${{ vars.BUILD_ECR_URL }}/${REPO_NAME}:latest
              docker push ${{ vars.BUILD_ECR_URL }}/${REPO_NAME}:latest
      - name: Logout from Docker hub
        run: docker logout
